### ISSUE TITLE
add storage_tiering_debug_log option to plugin_specific_configuration

### ISSUE THREAD

**Issue by trel** [irods/irods_capability_tiered_storage#11]
The new parameter could be...
```
"plugin_specific_configuration": {
    "storage_tiering_debug_log" : "true",
}
```

If the code sees this setting set to `true`, fire rodsLog() when a data object is moved from one tier to another.

An alternate suggestion is to use a numerical `storage_tiering_log_level` (probably 6, 7, 8 to match iRODS, in general (default of 5 is relatively quiet)) and write more to the rodsLog appropriately.  6 would write when a file has been moved, 7 would show more context/timing/logic, 8 would add ... ?

**Comment by jasoncoposky** [comment]
Consider the usage of strings mapping back to the rodsLog.h values:
```
LOG_DEBUG10
LOG_DEBUG9
LOG_DEBUG8
LOG_DEBUG7
LOG_DEBUG
LOG_DEBUG6
```
which will define the actual log level for the storage tiering plugin.  This will keep the plugin in sync with future log improvements.
