### ISSUE TITLE
add metadata flag to set minimum restage tier

### ISSUE THREAD

**Issue by jasoncoposky** [irods/irods_capability_tiered_storage#12]
Users may not wish to restage data back to the lowest tier.  Provide a flag to tag a resource indicating it is the minimum tier to restage data.

**Comment by trel** [comment]
so a resource will have an annotation that says do not pass me on the way back to tier 0?

1.
```
tier 0
tier 1 - irods::storage_tier_restage_target=true
tier 2 - irods::storage_tier_restage_target=true
tier 3 - has file
```
2. `iget file`
3. ?

After restage, is the file now in tier 1 or tier 2?

What is a better flag name?  Is true/false not the best choice?

**Comment by jasoncoposky** [comment]
irods::minimum_restage_tier ?

**Comment by trel** [comment]
on what resource?    and what's the value?

**Comment by jasoncoposky** [comment]
irods::storage_tier_minimum_restage_tier flags the resource in the group which is the end of the line for restaging.  if it is not present then the default is the lowest tier index value.  the value of the attribute is irrelevant, it simply acts as a flag.

**Comment by jasoncoposky** [comment]
- [ ] add requirement of 'true' value to the minimum restage tier attribute
- [ ] add docs to README.md
- [ ] error on multiple tags - chose first from sorted results, log error

**Comment by trel** [comment]
and update all metadata attributes to be of the form `irods::storage_tiering::minimum_restage_tier`

**Comment by jasoncoposky** [comment]
Test does not need to tier data to Tier 2 before testing the restage.  Put data into Tier 2 and then test restage, which saves time in CI.
