### ISSUE TITLE
enhance plugin to support the specific query interface

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_tiered_storage#19]
Since iquest does not support OR condition,  we want to use specific query interface to define saved query as shown and then add the save query as custom violating objects query but it throws an error "query fill failed for [iquest --sql storage_tier_query_example]".

# setup saved queries
iadmin asq "select distinct R_DATA_MAIN.data_name ,R_COLL_MAIN.coll_name from  R_DATA_MAIN , R_RESC_MAIN , R_COLL_MAIN , R_META_MAIN  , R_OBJT_METAMAP r_data_metamap  where R_DATA_MAIN.resc_id IN ('19012') AND ((R_META_MAIN.meta_attr_name = 'irods::access_time'  AND R_META_MAIN.meta_attr_value < ?) OR (R_META_MAIN.meta_attr_name = 'ARCHIVE' AND R_META_MAIN.meta_attr_value = 'Y')) AND R_COLL_MAIN.coll_id = R_DATA_MAIN.coll_id  AND R_RESC_MAIN.resc_id = R_DATA_MAIN.resc_id  AND R_DATA_MAIN.data_id = r_data_metamap.object_id  AND r_data_metamap.meta_id = R_META_MAIN.meta_id  order by R_COLL_MAIN.coll_name, R_DATA_MAIN.data_name" storage_tier_query_example;

iquest --sql storage_tier_query_example "1520907681"
 tiering_test.txt
/TestZone/home/rods

# added custom query to root resource throws an error as shown in the screenshot.
imeta set -R fastResc irods::storage_tier_query "iquest --sql storage_tier_query_example"

![saved query error](https://user-images.githubusercontent.com/13893698/37618312-1d82c206-2b73-11e8-8766-c392260303cc.png)

**Comment by jasoncoposky** [comment]
reopening, due to improperly tested query.
