### ISSUE TITLE
Move the metadata from Tier 0 to Archive Tier 1 in S3 Object storage

### ISSUE THREAD

**Issue by masilamani** [irods/irods_capability_tiered_storage#21]
when user-defined metadata is added to data object in Tier 0,  tiered storage framework is not moving the metadata along with data object into Archive Tier 1 in S3 Object storage.

Example:

imeta ls -d /DiaZone/home/rods/foo.txt
AVUs defined for dataObj /TestZone/home/rods/foo.txt:
attribute: ARCHIVE
value: Y
units: 

After it is moved into S3 object storage,  metadata shows empty when i run the aws s3api command as shown below.

aws s3api head-object --bucket <bucketname> --key 335321/foo.txt
{
    "AcceptRanges": "bytes", 
    "ContentType": "binary/octet-stream", 
    "LastModified": "Mon, 19 Mar 2018 02:19:23 GMT", 
    "ContentLength": 15, 
    "ETag": "\"1846010d59652a3bb045580a44b12cf3\"", 
    "Metadata": {}
}

But it should have like this if AVU metadata is also moved along with data object.

{
    "AcceptRanges": "bytes", 
    "ContentType": "binary/octet-stream", 
    "LastModified": "Mon, 19 Mar 2018 02:19:23 GMT", 
    "ContentLength": 15, 
    "ETag": "\"1846010d59652a3bb045580a44b12cf3\"", 
    "Metadata": {
           "archive": "Y"
     }
}

**Comment by jasoncoposky** [comment]
This feature request would be more appropriate for the [S3 Plugin](https://github.com/irods/irods_resource_plugin_s3)
